[module]
  [[module.imports]]
    path = "github.com/Lednerb/bilberry-hugo-theme/v3"
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify-cms"
    path = "github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify"
    path = "github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5"